apiVersion: v2
type: application
name: trilium
home: https://github.com/mmoerz/triliumnext
icon: https://github.com/mmoerz/triliumnext/commit/icon.png
deprecated: false
description: |-
  Build your personal knowledge base with Trilium Notes. A hierarchical note taking application with focus on building large personal knowledge bases.
annotations:
  category: Notes
version: 1.3.0
appVersion: 0.92.4
kubeVersion: ">= 1.19"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 3.3.2
keywords:
  - electron
  - wiki
  - notebook
  - notes
  - self-hosted
  - knowledge-graph
  - electron-app
  - note-taking
  - self-hosting
  - knowledge-base
  - personal-knowledge-base
  - knowledge-management
  - personal-wiki
  - notes-app
  - scriptable
  - knowledge-management-graph
  - note-managment
  - note-taker
  - local-first
maintainers:
  - name: triliumnext
    url: https://github.com/mmoerz/triliumnext/Notes
    email: michael@moerz.co.at
sources:
  - https://github.com/mmoerz/triliumnext/helm-charts
  - hhttps://github.com/mmoerz/triliumnext/Notes
